#!/bin/sh

ROFI_THEME="$XDG_CONFIG_HOME/rofi/themes/no-icon.rasi"

res=$(fd . $HOME -e pdf | xargs -I{} basename "{}" | sort -u | rofi -dmenu -p "open: " -i -theme $ROFI_THEME)
if [ -z "$res" ]; then
  exit 0
fi

res=$(fd "$res" $HOME | sed "s|$HOME|~|" | sed "s| |\n|")

if [ $(echo "$res" | wc -l) -gt 1 ]; then
  res=$(echo -en "$res" | rofi -dmenu -p "Choose path: " -i -theme $ROFI_THEME)
fi
res=$(echo $res | awk '{print $1}' | sed "s|~|$HOME|")

if [ -z "$res" ]; then
  echo "Empty filename."
else
  if [ -f "$res" ]; then
    echo "Opening $res"
    zathura $res &
  else
    echo $res
    echo "Invalid filename."
  fi
fi
