#!/usr/bin/env bash

CONFIG_FILES="$HOME/.config/waybar/config.jsonc $HOME/.config/waybar/style.css"

trap "killall waybar" EXIT

waybar &
fswatch --event Updated $CONFIG_FILES | while read STDOUT; do
    killall waybar
    waybar &
done
