#!/bin/sh

#     decoration:blur:enabled = false and decoration:drop_shadow = false to disable fancy but battery hungry effects.
#
#     misc:vfr = true, since it’ll lower the amount of sent frames when nothing is happening on-screen.

MODE_FILE=$XDG_CACHE_HOME/lpmmode
icon_name=$XDG_CONFIG_HOME/hypr/icons/low-bat.png
G14=0

on() {
  hyprctl eval 'hl.config({ decoration = { blur = { enabled = false }, shadow = { enabled = false }}, animations = { enabled = false }})'
  if [ $G14 -eq 1 ]; then
    asusctl anime -b Off
  fi
  notify-send "Low Power Mode" "on" -i $icon_name -u normal -h string:x-canonical-private-synchronous:test -h boolean:SWAYNC_BYPASS_DND:true -h int:transient:1
  echo on > $MODE_FILE
}

off() {
  hyprctl eval 'hl.config({ decoration = { blur = { enabled = true }, shadow = { enabled = true }}, animations = { enabled = true }})'
  if [ $G14 -eq 1 ]; then
    asusctl anime -b Low
    asusctl anime gif -p $XDG_CONFIG_HOME/hypr/asus_anime/pikachu_running.gif -l 0 &
  fi
  notify-send "Low Power Mode" "off" -i $icon_name -u normal -h string:x-canonical-private-synchronous:test -h boolean:SWAYNC_BYPASS_DND:true -h int:transient:1
  echo off > $MODE_FILE
}

case "$1" in
  start)
    if [ -f $MODE_FILE ] && [ -n "$(cat $MODE_FILE)" ]; then
      $(cat $MODE_FILE)
    fi
    ;;
  on)
    on
    ;;
  off)
    off
    ;;
  toggle)
    if [ -f $MODE_FILE ] && [ -n "$(cat $MODE_FILE)" ]; then
      MODE="$(cat $MODE_FILE)"
      if [ $MODE = "on" ]; then
        off
      else
        on
      fi
    else
      on
    fi
    ;;
  *)
    echo 'usage: lowpowermode [on|off]'
    ;;
esac
