#!/bin/sh

#     decoration:blur:enabled = false and decoration:drop_shadow = false to disable fancy but battery hungry effects.
# 
#     misc:vfr = true, since it’ll lower the amount of sent frames when nothing is happening on-screen.

MODE_FILE=/tmp/lpmmode
icon_name=$XDG_CONFIG_HOME/hypr/icons/low-bat.png

on() {
  hyprctl keyword decoration:blur:enabled false
  hyprctl keyword decoration:shadow:enabled false
  hyprctl keyword animations:enabled false
  hyprctl keyword misc:vfr true
  dunstify "Low Power Mode" "on" -i $icon_name -u normal -h string:x-canonical-private-synchronous:test
  echo on > $MODE_FILE
}

off() {
  hyprctl keyword decoration:blur:enabled true
  hyprctl keyword decoration:shadow:enabled true
  hyprctl keyword animations:enabled true
  hyprctl keyword misc:vfr false
  dunstify "Low Power Mode" "off" -i $icon_name -u normal -h string:x-canonical-private-synchronous:test
  echo off > $MODE_FILE
}

case "$1" in
  on)
    on
    ;;
  off)
    off
    ;;
  toggle)
    if [ -f $MODE_FILE ] && [ -n "$(cat $MODE_FILE)" ]; then
      MODE="$(cat $MODE_FILE)"
      if [ $MODE = "on" ]; then
        off
      else
        on
      fi
    else
      on
    fi
    ;;
  *)
    echo 'usage: lowpowermode [on|off]'
    ;;
esac
