#!/bin/dash

actions="󰐥 poweroff\n reboot\n reboot (choose boot entry)\n lock\n󰍃 logout"

result=$(echo "$actions" | rofi -dmenu -l 5 -p "󰐦: ")


case "$result" in
  "󰐥 poweroff")
    poweroff
  ;;
  " reboot")
    reboot
  ;;
  " reboot (choose boot entry)")
    entry=$(ls /boot/loader/entries/ | rofi -dmenu -l 4 -p "Next entry: ")
    if [ -n "$entry" ]; then
      bname=$(echo $entry | awk -F. '{print $1}')
      echo $bname
      continue=$(echo "YES\nNO" | rofi -dmenu -l 2 -p "Boot to $bname?: ")
      if [ "$continue" = "YES" ]; then
        systemctl reboot --boot-loader-entry=$entry
      fi
    else
      echo test
      notify-send -r 820 -u low -i ~/.config/waybar/icons/dialog-error.svg\
        "Power menu" "No boot entry selected"\
        -h string:synchronous:test\
        -h boolean:SWAYNC_BYPASS_DND:true
    fi
  ;;
  " lock")
    hyprlock
  ;;
  "󰍃 logout")
    pkill -u $USER
  ;;
  *)
    :
  ;;
esac
