[manager]
prepend_keymap = [
  { on = "q", run = "quit --no-cwd-file", desc = "quit without cd"},
  { on = "Q", run = "quit", desc = "quit with cd"},
  { on = [ "<C-n>" ], run = '''
    shell 'dragon-drop -x -T "$1"' --confirm
    ''', desc = "drag and drop"}
]
