background = 0xFF24283B
base = 0xFF1D202F
alternate_base = 0xFF414868
text = 0xFFF8F8F2
bright_text = 0xFFF8F8F2
accent = 0xFFC0CAF5
accent_secondary = 0xFFFDCFFF
font_family = Noto Sans
font_family_monospace = Noto Sans Mono
h1_size = 24
h2_size = 19
h3_size = 15
font_size = 12
small_font_size = 11
rounding_large = 5
rounding_small = 2
