local hyprDir = os.getenv("XDG_CONFIG_HOME") .. "/hypr"
local scriptDir = hyprDir .. "/scripts"
hl.on("hyprland.start", function () 
  -- hl.exec_cmd("hyprpaper > /tmp/hyprpaper.log")
  -- hl.exec_cmd("$scriptDir/launch_waybar")
  hl.exec_cmd("qs -nd")
  hl.exec_cmd("killall dunst")
  -- hl.exec_cmd("qs -nd -c /home/samuelhernandes/Dokumente/srcs/nixnew/modules/user/modules/quickshell/shell")
  -- hl.exec_cmd("asusctl anime --off-when-unplugged true --off-when-suspended true gif -p $hyprDir/asus_anime/pikachu_running.gif -l 0")
  hl.exec_cmd(string.format("%s/lowpowermode start", scriptDir))
  -- hl.exec_cmd("swaync")
  hl.exec_cmd("copyq --start-server")
  hl.exec_cmd("xfce4-power-manager")
  -- hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("nm-applet --sm-disable")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("hypridle > /tmp/hypridle.log")
  hl.exec_cmd("amixer -c 2 sset 'Mic Boost',0 0 &> /dev/null")
  hl.exec_cmd(string.format("%s/start_mpd &", scriptDir))

  hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme AC-Future")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 36")
end)
